trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'windows-2019'

variables:
  buildConfiguration: 'Debug'

steps:
- task: DotNetCoreInstaller@0
  displayName: Install .NET Core SDK
  inputs:
    packageType: 'sdk'
    version: '2.2.202' 
 
- task: DotNetCoreCLI@2
  displayName: Build project
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: test
    projects: 'src/ESLint.MSBuild.Tests/ESLint.MSBuild.Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: Generate NuGet package
  inputs:
    command: pack
    packDirectory: '$(Build.ArtifactStagingDirectory)/packages'
 
- script: |
    for file in $(Build.ArtifactStagingDirectory)/packages/*; do   
        echo "##vso[task.setvariable variable=ESLINT_NUGET_PACKAGE]$(basename $file)";
    done;
  displayName: Set package filename

- task: PublishBuildArtifacts@1
  displayName: Publish artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/packages/$(ESLINT_NUGET_PACKAGE)'
    artifactName: Package